### ISSUE TITLE
Adding the subtype Icn

### ISSUE THREAD

**Issue by rjoebruch** [profjsb/timedomain-taxonomy#13]
Hello! following the publication of these: 
https://ui.adsabs.harvard.edu/abs/2021TNSAN..76....1G/abstract  
https://arxiv.org/pdf/2111.12435.pdf  
https://arxiv.org/pdf/2111.12110.pdf 
Could you add the subtype "Icn" to the taxonomy? 

Best!

**Comment by rjoebruch** [comment]
@adamamiller

**Comment by profjsb** [comment]
Closed by #15
